[package]
name = "allpaka-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "allpaka"
path = "src/main.rs"

[dependencies]
allpaka-core.workspace = true
allpaka-gguf.workspace = true
allpaka-backend.workspace = true
allpaka-model.workspace = true
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
